---
- hosts: haproxy
  user: root
  tasks:

  - name: Install apache package.
    action: apt pkg=apache2 state=installed

  - name: Start apache service.
    action: service name=apache2 state=started

  handlers:

  - include ../handlers/apache-handlers.yml
