- hosts: siege
  user: root
  tasks:

  - name: Install siege package.
    action: apt pkg=siege state=installed

  - name: Install siege URLs list.
    action: copy src=../files/siege-urls.txt dest=/etc/siege/urls.txt owner=root group=root mode=0644

  - name: Install siege configuration file.
    action: copy src=../files/siege-siegerc dest=/etc/siege/siegerc owner=root group=root mode=0644

  - name: Install siege background script
    action: copy src=../files/siege-background dest=/usr/bin/siege_bg owner=root group=root mode=0755

  - name: Add Jackson SSH key
    action: authorized_key user=root key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5+ZvXWGXcK/o7XzhOzCYU+CTv6rKkVn1gGtVF5l8f3fij450i3YriQJRAgd+wS4q3Ko0wJK3nya7CQtppmuQCEYfmjhKHbizhTLrgDNKZ3cPt3InfsWX1J2f/e4CWCmT9CSdRw5q0bxm4J6DPLweIUIuO9P7kpJ8ZwuuV3kmRcWS68jljEutXhP7NfvDFoIl1gOSFIrusDQIYYY1b7U3MdeT/gZtA3OtLWDRAPJcZAIq00NXh4Ct02zBl1QzBre4WQu2JIRQYYdBSqLLZXwx3WFEtEvHpq0TcVSGURqHpm9ln22zaqSKbYmlPwJmpTJCPZbUvGlIchQKDU4s0hWVR jackson@roundhouseagency.com"

  handlers:
    - include: ../handlers/siege-handlers.yml